### ISSUE TITLE
Couldn't start the server using nodejs

### ISSUE THREAD

**Issue by ysihaoy** [reactjs/react-tutorial#60]
The error is:

module.js:338
    throw err;
          ^
Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/tianhao/Project/ReactProject/react-tutorial/server.js:15:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)

**Comment by grantgeorge** [comment]
Try

    Npm install express

**Comment by zpao** [comment]
The readme says to run `npm install`, which should install `express` (and any other dependencies). I'm going to close out but feel free to reopen if that still doesn't fix it and I'll investigate.
